language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
before_script:
- git config --global user.email "gerald.oyudo@gmail.com"
- git config --global user.name "Gerald Oyudo"
env:
  global:
    secure: F5nTv6+tPZlI0o4QfYrxFXdCnB/fe62ay/t1X0Zjo7rajjjVACibUuvyEU6MppYHUiKv6VnQTfFD37RvQKV3UCZ1MkzlLgZFs30515HIzzWXh1Paen0AyqMqFRalUJDa1nlgTJPeTlCnZZniFYznbfZ5QW3vfhEnHUpVBtCvgBwwQQ3MF22Zvb2m+7UqrJIsdFNlxLBu/wXEYmH0fwrO/TWEzP9/nqeQQ315yB/jV8kni9VjDFP62ZxLen75tf7HX9aMWSIGpDQ453EreVqq01ySKtE38mYMwE9JQTaIjKIDsRmrsku4Pv2MD96Ci8G0FkoFE2jet0LUiz5YB9bQDR0BiZuA6umj/1ZSHQYMCiPYtlIyAcZCWKMfozF6J3c6y67emzVwuHlBZTX2D4V6C+nCso+WLEVAj0e5QwlLXxk0xd38qPmwCt0tVk29Llnz4+3VV9k3jIRkhKzQ+dfnKK0j4r+VDij7elLL3EWS9AlbEsaqD45S/2TIR1T0QUBMKwKoWklMKa02p7673avdqfvU4Of+YKmymoF/zL5DrdPkbYFSXDwukxNeoJDCvyMe8Lk+bDjRY1kD3aHKMiyfwqBpkLFrusaDAfNn2TL/d3qWmfw4wyIjClTY7hTfUIys5hqMvZU9zZ9HNzxoR+1V1D+FS8qeb8BsuHWLtFFSp3g=
