# Welcome to Jekyll!

# Website settings
title: "Prime Devs"
description: "Gerald's Blog"
keywords: "Gerald, Prime Devs,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Gerald'
  first_name: 'Gerald'
  last_name: 'Oyudo'
  email: 'gerald.oyudo@gmail.com'
  facebook_username: 'gerald_oyudo'
  github_username: 'geraldoyudo'
  avatar: 'static/img/landing/Gerald.jpg'
  desc: 'I am a full stack developer who play with new technologies and learn about new concepts. I believe that programming is key to technological development'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: prime-devs
  public_key: 0YCfGwO4Nhz4lj7mNVUA0THiuSbjnza68Qp26zxZ61UqLrQOwoUE7jCPrmrmGx1w

# share
bshare:
  # uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - icons=font
    - source-highlighter=pygments
    - pygments-css=style